import 'dart:async';
import 'dart:convert';

import 'package:amide_app/features/data/models/records/vital_sub.dart';
import 'package:amide_app/features/data/models/reminder/music.dart';
import 'package:firebase_database/firebase_database.dart';

class Realtime {
  final DatabaseReference alarm_db = FirebaseDatabase.instance.ref("alarms");

  Future<void> createData(Music music) async {
    String? autoGeneratedId = alarm_db.push().key;

    final int id = int.parse(music.id!.replaceAll("-", "").substring(0, 4), radix: 16);

    await alarm_db.child(autoGeneratedId!).remove().then(
          (value) => alarm_db.child("$id").set(music.toJson()),
        );
  }

  Future<void> editData(Music music) async {
    final int id = int.parse(music.id!.replaceAll("-", "").substring(0, 4), radix: 16);
    await alarm_db.child("$id").update(music.toJson());
  }

  Future<void> deleteData(Music music) async {
    await alarm_db.child(music.id!).remove();
  }

  final DatabaseReference vital_db = FirebaseDatabase.instance.ref("vitals");

  Future<void> recordData() async {
    await vital_db.update({
      "heartRate": -1,
      "height": -1,
      "weight": -1,
      "oxygenRate": -1,
      "temperature": -1,
    });

    print("Set to -1");
    await sendData();
  }

  VitalSub vital = VitalSub();

  Future<dynamic> sendData() async {
    vital_db.onValue.listen(
      (event) {
        DataSnapshot snapshot = event.snapshot;
        if (snapshot.value != null) {
          String jsonString = json.encode(snapshot.value);

          Map<dynamic, dynamic> data = json.decode(jsonString);

          final temperature = data["temperature"];
          final height = data["height"];

          vital = VitalSub.fromJson(data as Map<String, dynamic>);

          print(temperature);
          print(height);
        }
      },
    );
  }
}
