import 'dart:async';

import 'package:amide_app/features/data/models/reminder/music.dart';
import 'package:amide_app/features/data/provider/recording.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:provider/provider.dart';

class Realtime {
  final DatabaseReference alarm_db = FirebaseDatabase.instance.ref("alarms");

  Future<void> createData(Music music) async {
    String? autoGeneratedId = alarm_db.push().key;

    final int id = int.parse(music.id!.replaceAll("-", "").substring(0, 4), radix: 16);

    await alarm_db.child(autoGeneratedId!).remove().then(
          (value) => alarm_db.child("$id").set(music.toJson()),
        );
  }

  Future<void> editData(Music music) async {
    final int id = int.parse(music.id!.replaceAll("-", "").substring(0, 4), radix: 16);
    await alarm_db.child("$id").update(music.toJson());
  }

  Future<void> deleteData(Music music) async {
    await alarm_db.child(music.id!).remove();
  }

  final DatabaseReference vital_db = FirebaseDatabase.instance.ref("vitals");

  /// [recordData] when the check all equipments tap the done
  /// it will set the vital signs to -1

  Future<void> recordData(context) async {
    await vital_db.update({
      "heartRate": -1.0,
      "height": -1.0,
      "weight": -1.0,
      "oxygenRate": -1.0,
      "temperature": -1.0,
    });

    print("Set to -1.0");
    await listenData(context);
  }

  /// [sendData] setting up the vital signs from the arduino
  /// to change the -1 to its specific value
  Future<dynamic> listenData(context) async {
    vital_db.onValue.listen((event) {
      print("hi");
    });
  }

  void getData(context) async {
    final RecordServices record = Provider.of<RecordServices>(context, listen: false);
    await vital_db.get().then((value) {
      print(value.value);
      Object? vital = value.value;
      Map<String, dynamic> map = (vital as Map<dynamic, dynamic>).cast<String, dynamic>();

    });
  }
}
