import 'package:amide_app/features/data/models/reminder/music.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:uuid/uuid.dart';

class Realtime {
  final DatabaseReference db = FirebaseDatabase.instance.ref("alarms");

  final Uuid uuid = const Uuid();

  void createData(Music music) {
    final uid = uuid.v4();
    final int id = int.parse(uid.replaceAll("-", "").substring(0, 4), radix: 16);

    String? autoGeneratedId = db.push().key;
    db.child(autoGeneratedId!).remove().then(
          (value) => db.child("$id").set(music.toJson()),
        );
  }
}
