// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuf6YfYifUCjvBSbCi1cNLV_zE6L4XY7k',
    appId: '1:508133188397:web:2c3b1dffa13f15ba6869a4',
    messagingSenderId: '508133188397',
    projectId: 'amide-thesis',
    authDomain: 'amide-thesis.firebaseapp.com',
    databaseURL: 'https://amide-thesis-default-rtdb.firebaseio.com',
    storageBucket: 'amide-thesis.appspot.com',
    measurementId: 'G-7V3L55K668',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XfrFXvA43QdB8ZHE9PL4fafWq7gbWcc',
    appId: '1:508133188397:android:cb0c20c4c3c4a6466869a4',
    messagingSenderId: '508133188397',
    projectId: 'amide-thesis',
    databaseURL: 'https://amide-thesis-default-rtdb.firebaseio.com',
    storageBucket: 'amide-thesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXfckrMg2eSfPVfgbJ7FTEIBiV3xXZA4',
    appId: '1:508133188397:ios:903cba89cb082ecb6869a4',
    messagingSenderId: '508133188397',
    projectId: 'amide-thesis',
    databaseURL: 'https://amide-thesis-default-rtdb.firebaseio.com',
    storageBucket: 'amide-thesis.appspot.com',
    iosClientId: '508133188397-9ttr4ejers2drc9ipahh986m7rcbvnc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXfckrMg2eSfPVfgbJ7FTEIBiV3xXZA4',
    appId: '1:508133188397:ios:fe8baa5b2b4f26b06869a4',
    messagingSenderId: '508133188397',
    projectId: 'amide-thesis',
    databaseURL: 'https://amide-thesis-default-rtdb.firebaseio.com',
    storageBucket: 'amide-thesis.appspot.com',
    iosClientId: '508133188397-amjfdqv49aqksrfhqodmen98mrs6siko.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
